# Generated by Django 5.0.2 on 2025-02-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('todo', 'Padaryti'), ('doing', 'Daroma'), ('done', 'Atlikta'), ('rejected', 'Atmesta')], max_length=20),
        ),
    ]
